name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test on iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          xcodebuild build-for-testing -scheme "swift-bson" -destination "platform=iOS Simulator,name=iPhone 13"
      - name: Test
        run: |
          xcodebuild test-without-building -scheme "swift-bson" -destination "platform=iOS Simulator,name=iPhone 13"
